[features]
seeds = false
skip-lint = false
[programs.localnet]
stream_contract = "HSmCq1hyEyUcrKqwEeW2nneDqfcC6ZP7iqfcyuJmgpn3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/vineetkinger/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
